import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import ConvexClientProvider from "@/components/providers/ConvexClientProvider";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";




const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>    
      <html lang="en">
      <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col`} 
          style={{ minHeight: '100vh', background: 'linear-gradient(to bottom, #141414, #1a1a1a)', color: '#f7f7f7' }}
        >
          <ConvexClientProvider>
            {children}
          </ConvexClientProvider>

          
          <Footer />
          <Toaster/>
        </body>
      </html>
    </ClerkProvider>
  );
}
